---
- name: Restart Syncthing service for the user
  ansible.builtin.systemd:
    name: syncthing
    scope: user
    state: restarted

- name: Update apt repository
  become: True
  changed_when: false
  ansible.builtin.apt:
    update_cache: true

